name: Homebrew bump formula
description: Bump (update) a Homebrew formula on new project release
author: dawidd6
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: Github token (not the default one)
    required: true
  formula:
    description: Formula name
    required: true
  tap:
    description: Formula tap
    required: false
  force:
    description: Check open PRs or not
    required: false
runs:
  using: docker
  image: Dockerfile
