name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formula:
          - test-formula-url
          - test-formula-git-revision
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          formula: ${{matrix.formula}}
          tap: dawidd6/homebrew-test